name: Docs Deployment  
  
on:  
  push:  
    branches: [ main ]  
  
jobs:  
  docs:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2  
      - name: Install Rust  
        uses: actions-rs/toolchain@v1  
        with:  
          toolchain: stable  
          override: true  
      - name: Generate Docs  
        run: cargo doc --no-deps  
      - name: Deploy Docs  
        uses: peaceiris/actions-gh-pages@v3  
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./target/doc
